### ISSUE TITLE
Udpate content for CCC Transcript Legends and Transcript Request Forms page 

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#102]
http://dev-ccc-transfer.gotpantheon.com/ccc-transcript-legends-and-transcript-request-links

Source: http://ccctransfer.org/ccc/ccc-transcript-legends-and-request-links

**Comment by DirectorWho** [comment]
This has been updated. Simple find & replace to update incorrect pathing.

**Comment by ghost** [comment]
Thanks. Closing
