### ISSUE TITLE
Add anchor tags for in page menus on CCC Athletic Counseling Toolbox

### ISSUE THREAD

**Issue by AMagnifico** [woodwarddesign/ccc-transfer#103]
source: http://ccctransfer.org/ccc/athletic-toolbox

http://dev-ccc-transfer.gotpantheon.com/ccc-athletic-counseling-toolbox

**Comment by ghost** [comment]
@DirectorWho 

CCC Links > Athletic Toolbox 

The link for _Participating, Nationwide NCAA & NAIA University Campus Snapshots_ is broken. 
http://dev-ccc-transfer.gotpantheon.com/ccc-athletic-counseling-toolbox#top 
If you click on _Participating, Nationwide NCAA & NAIA University Campus Snapshots_ it goes to a dead page.  
http://dev-ccc-transfer.gotpantheon.com/campus-snapshots-31/oos-campus-snapshots

The original page http://ccctransfer.org/ccc/athletic-toolbox links to http://ccctransfer.org/campus-snapshots-31/oos-campus-snapshots

**Comment by ghost** [comment]
@DirectorWho 
Is it me? The link still seems broken. Do leave me notes if you move stuff over to Done _s'il te plaît_

**Comment by DirectorWho** [comment]
@wdg-thomas it wasn't you. I missed a link. Nice catch, fixed.
