### ISSUE TITLE
Resize columns when sorting on School Search page

### ISSUE THREAD

**Issue by bodhiprice** [woodwarddesign/ccc-transfer#106]

**Comment by bodhiprice** [comment]
Ok, I have this finished, but it needs testing. The page is here:
http://dev-ccc-transfer.gotpantheon.com/school-search
This was a bit tricky because it has to work with the MixitUp plugin which has a delay to its action so it produces the cool sorting effect.

**Comment by ghost** [comment]
nicely done. closing
