### ISSUE TITLE
Menu: CCC Links: Missing "CCC Student Service Program Link" 

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#107]
Make dup pages as recommended

**Comment by bodhiprice** [comment]
Done.

**Comment by ghost** [comment]
Discussed with John. Need to educate client on best practices. John added to the page: 

> This page is a placeholder. On the old version of the site, two menu links went to the same page. This can be confusing for users. It's recommended that this page be provided fresh, unique content or be deleted.
