### ISSUE TITLE
Make textboxes bigger

### ISSUE THREAD

**Issue by bodhiprice** [woodwarddesign/ccc-transfer#114]
I forgot that Ruth asked me on our call if the text boxes could be bigger.

**Comment by DirectorWho** [comment]
@friendlymachine Text boxes? --> Content? Body section within the admin theme? Something else?

**Comment by bodhiprice** [comment]
@DirectorWho It's the text boxes on forms - login page, node edit, etc. The text is being cut off for her - I'd make them 30% taller. I'll do the ones for the admin theme.

**Comment by DirectorWho** [comment]
Alright, i'll take a look.

**Comment by bodhiprice** [comment]
I made the textboxes in admin theme bigger. Will leave default theme to Scott for design considerations.

**Comment by DirectorWho** [comment]
I did the same for the default theme.
