### ISSUE TITLE
On School Search page - School Filter is not displaying all States properly.

### ISSUE THREAD

**Issue by hmickelson** [woodwarddesign/ccc-transfer#115]
The OOS states stop with Nevada – we are missing the following states on the school listing:
1.   New Jersey
2.   New Mexico
3.   New York
4.   North Carolina
5.   Ohio
6.   Oklahoma
7.   Oregon
8.   Pennsylvania
9.   Texas
10. Utah
11. Washington
12. Wisconsin

**Comment by bodhiprice** [comment]
These states have been added to the filter.
