### ISSUE TITLE
Add a floating "back to the top" button to lower left upon scroll

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#117]
Example (however hideous) http://www.paradiseweatherwatch.com/ 

Style as well.

**Comment by bodhiprice** [comment]
@wdg-thomas @DirectorWho I have the link in place. I tried to put as much css in the theme as possible (_misc.scss) so you could change it if you want. It will appear as you scroll on long pages in the lower right. I tried it on the left and it would drive me insane to have that on a site I had to use everyday. Hopefully it is OK.
