### ISSUE TITLE
School Search:  Add search specifically by school name, just below "Filter Schools" with placeholder "Search by school name…"

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#119]
![school search - add search](https://cloud.githubusercontent.com/assets/7529130/3388473/7d599ec0-fc88-11e3-8708-c6393f38cbd4.png)

@DirectorWho theme after dev

**Comment by bodhiprice** [comment]
My config is done, but styling is still outstanding. @DirectorWho are you handling styling? There is a selection box on top form. I can't hide it in settings - probably OK to hide in CSS.
