### ISSUE TITLE
CCC Links: Equivalency Table: Restructure? 

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#120]
RE: Equivalency Table:http://dev-ccc-transfer.gotpantheon.com/ccc-english-and-math-assessment-course-equivalency-table.  
1. Rename "Community College" to "School"
2. Move Campus type next to School? 
3. **Resctructure** to group by school type? They predominantly use community colleges. Can they put UC, CSU, etc at bottom group like on original? 

This is worth discussing with Ruth directly to calibrate between dev, time, and functionality. 

> Note: 90% of users will compare Community to Community.  Mike to talk to John about development. Rename "Community College" to "School" and move Campus over next to Comm. Coll.?

**Comment by ghost** [comment]
@friendlymachine  updated description

**Comment by DirectorWho** [comment]
I've renamed community college to school, and moved the location of campus, but but haven't touched the regrouping.

**Comment by DirectorWho** [comment]
@wdg-thomas @friendlymachine 

The grouping & shortcut links for this view have been updated. It should be noted that the letters that were there before are only commented out at this time incase anything needs to be reverted or if there is something i have overlooked.
