### ISSUE TITLE
Campus detail: Move the Transfer Contact to right column

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#122]
http://dev-ccc-transfer.gotpantheon.com/campus/csu-bakersfield

Underneath this will also go the Notes block—as separate issue

**Comment by bodhiprice** [comment]
The transfer contact info is actually on the right - when it's available. What happened in this case is that the admissions contact block was mis-labeled. I've corrected that and left admissions where is was.
