### ISSUE TITLE
CCC Links: Transfer Center Websites & Catalogs Links page missing

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#128]
http://ccctransfer.org/ccc/ccc-website-and-catalog-links-page
http://dev-ccc-transfer.gotpantheon.com/ccc-transfer-center-websites-catalog-links

**Comment by DirectorWho** [comment]
@wdg-thomas Migrated current html markup from the live site to the corresponding page on the new site. Saved as revision
