### ISSUE TITLE
Menu anchor and header issue? 

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#130]
From Ruth

> I have not found any Back to tops that need removing but I have noticed some anchors missing in the in-page menus (which I figured out how to insert and link to the right areas within the content myself) and I noticed that when an in-page menu item is selected the header of that section is cut off due to anchors that populated into the wrong places? 

I played around with the scholarships page and figured out how to set them to show properly and I have fixed them in that page.  I am now going back to the beginning of the menu items (in Resources menu) and fixing all pages that have an in-page menu where the anchors do not point in the page content properly.

**Comment by DirectorWho** [comment]
All of the in content menus were working after i went through them last time. The resources page appears to have been updated recently. This is also a content issue  and won't have an affect on development.
