### ISSUE TITLE
Listserv sign up box cuts off bottom half of text fields

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#142]
From Ruth: 

> I went into the listserv signup box and as you can see the text box only shows half the typed content. The bottom of the name and email address are cut off. Can you expand the text cell a bit so the entries are fully visible?
> However, the listserv app works – I received three emails – one indicating I changed my name – the other two indicating I am already signed up for the listserv. 

![image002](https://cloud.githubusercontent.com/assets/7529130/3529395/19e477cc-0799-11e4-941c-fca815a3b1a6.jpg)

**Comment by ghost** [comment]
Ok, so this for IE 10 :-/ 
I don't have IE 10 machine to test this on. 

![image001](https://cloud.githubusercontent.com/assets/7529130/3545784/bfd97ace-087a-11e4-8313-8f26fd25e049.png)
![image002](https://cloud.githubusercontent.com/assets/7529130/3545786/bfda2f6e-087a-11e4-9a6a-6cefa36b0717.png)
![image003](https://cloud.githubusercontent.com/assets/7529130/3545785/bfda1f2e-087a-11e4-8336-56c2276479bf.png)

**Comment by DirectorWho** [comment]
@wdg-thomas @friendlymachine It looks like she's running IE10 on windows 7. I tried testing that setup through browserstack, but I've had no luck replicating this on the beta site so far. 

I've also tried this on windows 8, using ie 9, 10, & 11. 

Anyone have any suggestions on where to go from here?

**Comment by bodhiprice** [comment]
@DirectorWho @wdg-thomas  That is an old screenshot. Have her show you/us on Skype. Take a look at the browser font settings if there is an issue. I also checked on IE 10 and it was fine for me as well.

**Comment by DirectorWho** [comment]
Browser font settings is a good call. She has notes on the old site in the technical support page about changing font settings in the browser to improve font legibility on their old site.
