### ISSUE TITLE
CSU Campuses: Remove text at bottom 

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#143]
On http://beta.ccctransfer.org/csu-campuses page

> Remove "Admission/Graduation Requirements - By Campus also located in the CSU Toolbox."

Client unable to remove

![screen shot 2014-07-09 at 3 58 34 pm](https://cloud.githubusercontent.com/assets/7529130/3532472/eefdb130-07bc-11e4-8e01-940f5c81cf39.png)

**Comment by ghost** [comment]
Assigned to @hmickelson but might need to be kicked over to @friendlymachine or @DirectorWho

**Comment by bodhiprice** [comment]
This is done.
