### ISSUE TITLE
Hide certain States from Filter Schools menu

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#145]
Go to: http://beta.ccctransfer.org/school-search

![screen shot 2014-07-09 at 5 01 34 pm](https://cloud.githubusercontent.com/assets/7529130/3532899/64eb21f4-07c5-11e4-987c-f36bf7353ad7.png)
1. Click on configure block
2. In the *\* Block body**, mark schools to hide below with `<!--   -->` e.g. `<!--              <div class="filter" data-filter=".AL">Alabama</div> -->`. You'll see a couple in there. This way if we have to turn them back on we can. 

Hide the following: 

a.   Arkansas
b.   Connecticut
c.   Delaware
d.   Florida
e.   Georgia
f.    Indiana
g.   Iowa
h.   Kansas
i.     Kentucky
j.    Louisiana
k.   Maine
l.     Maryland
m. Michigan
n.   Minnesota
o.   Mississippi
p.   Nebraska
q.   New Hampshire
r.    North Dakota
s.    Rhode Island
t.    South Carolina
u.   South Dakota
v.   Tennessee
w.  Vermont
x.   Virginia
y.   Wyoming

**Comment by bodhiprice** [comment]
I'd just like to note that I was specifically asked to add all those states. They weren't included originally but were added at client request.

**Comment by hmickelson** [comment]
This is done.

**Comment by ghost** [comment]
Closing.  Missed "Wyoming" but I easily removed. Thanks.
