### ISSUE TITLE
Pager styling is off on search pages

### ISSUE THREAD

**Issue by bodhiprice** [woodwarddesign/ccc-transfer#146]
@wdg-thomas While fixing search issue, I came across this. Maybe something for Scott, but will have to be pushed with floating link edit.

![screen shot 2014-07-10 at 9 46 12 am](https://cloud.githubusercontent.com/assets/2105211/3539252/f3fb9680-0838-11e4-9c58-522b82bdd7bb.png)

**Comment by DirectorWho** [comment]
This has been fixed on dev. I'm presuming we'll have to fix it there then package up any theme changes & ship them over.
