### ISSUE TITLE
Telephone link issue on mobile <a href="tel:

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#147]
The `<a href="tel` tag seems to possibly not be formatted in a way that mobile devices see two number: the first as a link, and the second as text.  Clicking on the first does not call, but shows `<a href` 

Ruth just wants the whole module that auto-turns the phone numbers into links turned off

**Comment by bodhiprice** [comment]
@wdg-thomas Can you point to where this is happening? I checked one campus listing on my mobile and it worked as expected.

**Comment by ghost** [comment]
Here is a specific example from Ruth: 

http://beta.ccctransfer.org/campus/csu-channel-islands

**Comment by bodhiprice** [comment]
Tested example page in both Android and iPhone and it works as expected. I don't see an issue here.

**Comment by ghost** [comment]
This is what I'm seeing on my iPhone (iOS 7.1.*).  Click on the numbers does nothing. Hunter reported actually getting an `<a href` to come up when clicking on a phone number, but I can't replicate that. 

![foto](https://cloud.githubusercontent.com/assets/7529130/3574739/2e072420-0b81-11e4-912a-3a0ecdac04ab.PNG)

**Comment by bodhiprice** [comment]
Ok, give it a look now. I made some changes and I think it's good now. The issue seemed to only be iOS.

**Comment by ghost** [comment]
I'll kick it over to client for review. I did get the `<ahref` to come up like Hunter saw.  But, if it's only isolated to iPhone, then maybe that's not something we have the time to pursue. 

Did you turn off that module all together? I would think that that would kill the double listing, but not my speciality. 

![foto](https://cloud.githubusercontent.com/assets/7529130/3575254/a69a02d6-0b86-11e4-87eb-a8750c74ed83.PNG)

**Comment by bodhiprice** [comment]
No, I didn't turn off the module. It's a somewhat important feature in my view. I made edits to the view and it resolved on the iPhone I have access to. I did test on iOS, but it was iPad. I assumed it would be the same, but it wasn't.

**Comment by ghost** [comment]
There's some extra code that's getting in here. Can you check it out? 

``` html
<a href="tel:<a href="tel:(805) 437-8500"> (805) 437-8500 </a>
">
<a href="tel:(805) 437-8500">(805) 437-8500</a>
```

Note: DevTools shows the `>` within its own `">"`

**Comment by bodhiprice** [comment]
I think you're looking at a cached page. I have retested this on an iPhone - iOS 7 - and it's fine. I've attached a screenshot of what I see in my dev tools.
![screen shot 2014-07-15 at 3 30 51 pm](https://cloud.githubusercontent.com/assets/2105211/3590237/c264ba3a-0c56-11e4-86f5-28b19b697c0e.png)
I still think this is fixed.

**Comment by ghost** [comment]
Re-sent to client for review

**Comment by bodhiprice** [comment]
You might remind her to clear cache on mobile. They are more aggressive with caching.

**Comment by ghost** [comment]
Her issue now is about how Skype treats the numbers as links. I said: 

> The link itself still functions. This is intentional and a good practice that will lend itself to users on pads or phones.  On the desktop, yes, if you click on it might "do" something if you have software installed that reads phone numbers, e.g. Google Voice, Skype, etc.  We would strongly recommend keeping the phone numbers as links for usability's sake.

**Comment by bodhiprice** [comment]
The syntax for those links is different for Skype - maybe newer versions of Skype work with tel:, but you used to have to use callto: in order for Skype to work. This is a huge usability enhancement for mobile users. Glad you're encouraging her to keep it.

**Comment by ghost** [comment]
speechless… 

Client &^@$%#@$#%^ response and request to kill feature: 

> When I run link checks the link check app continually halts at each phone number as asks what app (E.g. Skype) do I want to choose which is a real hassle when link checking.  I spoke with Ray and, from our travels across California providing trainings to CCC counselors, we both feel that the population is not sophisticated enough tot utilize that option – they would prefer “dialing”.  Ray prefers that it be deactivated – leave the number – just deactivate the link.

**Comment by bodhiprice** [comment]
Done.

**Comment by ghost** [comment]
thanks.  
![eeyore](https://cloud.githubusercontent.com/assets/7529130/3592234/bc358708-0c6e-11e4-8f0b-c8bcf1024d2e.jpg)
