### ISSUE TITLE
U. of Idaho logo too small message? 

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#153]
Client says: 

> I tried to insert the logo but it said the logo was too small.  I am not good with graphics – so please fix this issue for me ASAP

![universityofidaho](https://cloud.githubusercontent.com/assets/7529130/3588269/f677fb8a-0c41-11e4-9110-9b34cb05fb6d.jpg)

**Comment by DirectorWho** [comment]
This is done.

**Comment by ghost** [comment]
closing, thanks.
