### ISSUE TITLE
Homepage: Disassociate link from banner url (leave link on text)

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#154]
**Homepage**
Banner image does not need a link, just the image below it

**Comment by bodhiprice** [comment]
I hate to be "that guy" but this is common practice with features like this. The text doesn't look like a link and if the the image isn't clickable (as it is on ~90% of other sites with similar features) then the click through rate will likely be very low.

So, this shouldn't be done, is bad for usability, and certainly shouldn't be labeled a bug.

That said, if client insists, I will do it. I just feel lousy repeatedly implementing bad practices on this project. I take pride in my work and so I have to at least point out that this is not a good idea.

**Comment by bodhiprice** [comment]
Done.

**Comment by ghost** [comment]
thanks :frog:
closing
