### ISSUE TITLE
School Search: Windows 7: Firefox bug: Text cuts off bottom? 

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#155]
On this (crappy) screenshot you'll see IE on the left and Firefox on the right. You'll notice that the cursor is _above_ the text box.  Ideas? What can be done?  :facepunch: 

![ie vs ff](https://cloud.githubusercontent.com/assets/7529130/3593124/40e88180-0c7e-11e4-972b-828886692248.jpg)

**Comment by DirectorWho** [comment]
I cannot replicate this.
