### ISSUE TITLE
Homepage: Under-banner text link relative path issue

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#156]
A pasted in relative link for the banner text does not work. It adds a `%20` to the end of the url. 

Note: The image shows and initial `/` but this is _not_ how it was pasted in. 

![screen shot 2014-07-15 at 4 23 46 pm](https://cloud.githubusercontent.com/assets/7529130/3593564/c5a3fd78-0c88-11e4-8de6-a5c281bf0404.png)

**Comment by bodhiprice** [comment]
I think this is just a case of a bad path being added. There is a new link on that feature that points to an Excel sheet and it works properly.

**Comment by ghost** [comment]
:leftwards_arrow_with_hook: Correct me if I'm mistaken, but if she enters an absolute path 
http://beta.ccctransfer.org/sites/default/files/documents/toolboxes/UC%20Toolbox/UC%20Toolbox%202014-15/F2014-CCC-Transfer-Applicants-and-TAU-Count.pdf **with** the `http://beta.ccctransfer.org/` then when the site moves to www.ccctransfer.org won't the link to the beta. break?   It's in there with an absolute path again I see.

**Comment by DirectorWho** [comment]
I'm going to need some direction here. Currently there are _some_ styling options in the view being applied to the url, but they aren't doing anything. Perhaps if we changed the format to plain text and instructed Ruth on relative links? The other option is asking her to use absolute paths for the site when it's live, and not listed as beta. 

This particular instance is likely a bad url path, as john mentioned above. It is impossible to prove without ftp access and checking the url path. Her poor naming conventions in the file structure certainly doesn't make this any easier.

**Comment by bodhiprice** [comment]
There is an option I'd like to try, but I can't install the module. It looks like they've locked down ability to install modules because I'm getting a permissions error. I will contact their IT guy and see if he can help.

**Comment by bodhiprice** [comment]
Email has gone out to Jeff Holden.

**Comment by bodhiprice** [comment]
OK, I think this is resolved, but we'll need to keep an eye on it. When we go live on the 30th, we should keep an eye on this. The Pathologic module is being used to re-write the paths depending on the domain. I've applied the settings to all text formats.

**Comment by ghost** [comment]
:question: Will she use relative or abs paths? She's been instructed to use relative paths in the training video Mike made for her.

**Comment by bodhiprice** [comment]
It shouldn't matter. Pathologic allows you to use absolute paths and then it sorts it out for you when the domain changes. If she uses relative paths, that's fine too. This solution will catch anything else we may have missed across the site.
