### ISSUE TITLE
Core & Module Release / Pantheon Update Emails

### ISSUE THREAD

**Issue by mlwoodward** [woodwarddesign/ccc-transfer#164]
The client is receiving emails about Core & Module Updates.  We will be managing those and those email notifications should go to support@woodwarddesigngroup.

---

From the Client:

Hi Michael,

Seems I am still receiving these. :-)

Ruth De Tro
Program Administrator, Grants, Butte College Transfer Counseling Center
Webmaster, CCC Transfer Counselor Website (TCW)
http://www.ccctransfer.org
detroru@butte.edu
Desk: (530) 893-7644
Fax:    (530) 893-4314

---

From: detroru@butte.edu detroru@butte.edu
Sent: Friday, July 25, 2014 1:12 AM
To: Detro, Ruth
Subject: New release(s) available for CCC Transfer Counselor Website

Drupal core updates should be performed directly from your Pantheon dashboard
[1].

There is a security update available for your version of Drupal. To ensure
the security of your server, you should update immediately!

See the available updates page for more information:
http://beta.ccctransfer.org/admin/reports/updates

Your site is currently configured to send these emails only when security
updates are available. To get notified for any available updates,
http://beta.ccctransfer.org/admin/reports/updates/settings.

Core updates should be performed directly from your Pantheon dashboard:
https://dashboard.getpantheon.com/account

[1] https://dashboard.getpantheon.com/account

**Comment by ghost** [comment]
:checkered_flag: Changed address to support@ on beta (live) & dev site. I don't have a login to the test site, but it looks neglected anyway.

**Comment by ghost** [comment]
:checkered_flag:  Ok, problem finally solved.
Changed email at: http://beta.ccctransfer.org/admin/reports/updates/settings

**Comment by mlwoodward** [comment]
No additional emails have appeared in the last few days.  Closing issue.
