### ISSUE TITLE
Equivalency page: Move OOS to end of school section

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#165]
http://ccctransfer.org/ccc-english-and-math-assessment-course-equivalency-table

> 1. Move OOS to end of school sections (should be listed as CCC, CSU, UC and OOS).

**Comment by ghost** [comment]
:warning: I have sorted the topic navigation to show OOS at the end, but reordering the school sections themselves? That is an @friendlymachine thing he'd have to look at.

**Comment by DirectorWho** [comment]
@mlwoodward @wdg-thomas This is a bit vague. I'd get further clarification before we look into taking this any further.

**Comment by Ruth-DeTro** [comment]
Still showing Alameda as a 4th campus when only three campuses are selected. Of course I can't get it to replicate again as it seems like a phantom issue that only appears periodically.  I will screen print it when I do get it to come up again.

**Comment by mlwoodward** [comment]
Very strange.  I tested and it appears to be a phantom issue.  If you experience this again...here are a few items that would be helpful.

1) The screenshot
2) Time the tool was used and error occurred (want to check logs to see if error showed up)
3) Anything else that happened when you ran the comparison.  

I will run test a few times a day for the next few days to see if I can stumble on the issue too.

**Comment by Ruth-DeTro** [comment]
Understood., and not sure if this helps, but I was in middle of a presentation at advisory so could not do a screen shot, but can give an estimated time of 11:45 -12:00 as it was just before lunch yesterday (Nov. 12).  Nothing else odd happened when I ran the comparison - other than Alameda had no check mark in selection box but other campuses (Allan Hancock, Butte and CSU, Chico) did.

**Comment by Ruth-DeTro** [comment]
Hi,

Please see my comments on GitHub…. And I agree… it was an issue once before that no one could replicate and it seems to be a phantom issue.

**Comment by mlwoodward** [comment]
At this point I am going to close this issue for now.  I will continue doing random tests over the next few days.  If the issue shows up again, we will reopen the issue.
