### ISSUE TITLE
Banner images not randomizing on IE 9 & 10 

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#167]
> 1. CCCCO monitor & Ray prefers the images scroll randomly on their own.
>    a. Currently supposed to change on page refresh –This is correct for Fire Fox but not for Explorer - they don’t always change on refresh in IE. 

On IE 9 & 10 it doesn't appear to be randomly pulling a new image. It doesn't pull a new image.

**Comment by bodhiprice** [comment]
It does pull a new image, but not every time. This is caching at work. It helps make their site fast(er). I shortened the cache lifetime to 30 minutes but strongly discourage disabling of caching.

**Comment by ghost** [comment]
:checkered_flag: 
turned off caching for anon users.

**Comment by bodhiprice** [comment]
?!!
