### ISSUE TITLE
Search Schools: Titles overflow out of text box (older browsers only)

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#170]
> In Search Schools the school titles flow out of text box (again happens on older browsers).

**Comment by bodhiprice** [comment]
Which browsers, what pages? More details please

**Comment by ghost** [comment]
IE9: 
![screen shot 2014-08-04 at 4 20 33 pm](https://cloud.githubusercontent.com/assets/7529130/3804970/3a953e58-1c2e-11e4-9ea9-13a3d6e8e575.png)

IE10: 
![screen shot 2014-08-04 at 4 21 31 pm](https://cloud.githubusercontent.com/assets/7529130/3804972/4418032a-1c2e-11e4-8b68-67516919c7e6.png)
