### ISSUE TITLE
Main navigation: IE 9 & 10 bug: Dropdown arrows cutting off 

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#171]
![screen shot 2014-08-04 at 4 28 46 pm](https://cloud.githubusercontent.com/assets/7529130/3805015/2b0364b4-1c2f-11e4-9dfb-aea0a33c5eaa.png)

**Comment by Ruth-DeTro** [comment]
I cannot tell if this can be closed because we have newer versions on our PCs.

**Comment by mlwoodward** [comment]
I will test this and confirm that it has been updated.

**Comment by mlwoodward** [comment]
This is fixed.  I checked on both browsers and did further revising to fix the issue.
