### ISSUE TITLE
Equivalency Page: 3 or more selected schools includes extra un-selected school

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#172]
> 1. When selecting three or more schools an additional school show that was not picked (see Bob’s screen print example below).  Bob has IE 10 and still sees these glitches.

**Comment by ghost** [comment]
@mlwoodward 
We've looked at this under Win7 IE10 and cannot replicate this behavior.

**Comment by mlwoodward** [comment]
Fixed.
