### ISSUE TITLE
Dimming ability and automatic disclaimer for campuses with outdated content

### ISSUE THREAD

**Issue by mlwoodward** [woodwarddesign/ccc-transfer#183]

**Comment by mlwoodward** [comment]
Created element in content type.  Need to update default to Yes and update Panel view with style.

**Comment by mlwoodward** [comment]
Disclaimer to use: “You are seeing this notice because the campus has not verified the content as current.  We suggest that you contact the campus to confirm the information is accurate.  We look forward to receiving the updates so we can remove this notice.”

**Comment by mlwoodward** [comment]
Updated and will review with client in the morning.

**Comment by mlwoodward** [comment]
Ruth is reviewing with their team.

**Comment by Ruth-DeTro** [comment]
Hi Michael,

The team has decided that the red disclaimer box is very visible and "pops" at the user so no further graying of page or deactivation of links is required.  This one is done. :-)

**Comment by mlwoodward** [comment]
Perfect.  I will close this issue!
