### ISSUE TITLE
School Search Scroll

### ISSUE THREAD

**Issue by mlwoodward** [woodwarddesign/ccc-transfer#184]
School search bar is clunky.  Scroll Issues.

**Comment by Ruth-DeTro** [comment]
After returning from the advisory meeting it was noted that when clicking on "California" in the Campus Search menu scroll-down, only CSU and UCs appear and the AICCUs (which are located in California as well) do not show on the list.  Please fix by including all AICCUs in the Campus Search drop-down for California as well as AICCU. Call or email me if  you need more clarification. :-)

**Comment by mlwoodward** [comment]
We will check into this further.

**Comment by mlwoodward** [comment]
The AICCU content type does not declare location.  As such, it can not be filtered by state.  Sent message to @Ruth-DeTro to review possible options to make sure that they reach potential goals.

**Comment by mlwoodward** [comment]
I have fixed this issue and will do a short video and send to @Ruth-DeTro .

**Comment by mlwoodward** [comment]
@Ruth-DeTro all the AICCU schools have been updated.  I also sent the video tutorial over to you via email.  When adding the AICCU, the State field will automatically add CA.  If the AICCU school is not in state, please change state abbreviation to appropriate state.
