### ISSUE TITLE
Added a new PA campus to OOS page and now I have two PA sections and only one campus showing on campus drop-down for Pennsylvania (PA)

### ISSUE THREAD

**Issue by Ruth-DeTro** [woodwarddesign/ccc-transfer#187]
I have three new OOS campuses that I have to add today but I ran into an issue. Following your video on how to add a campus, I entered Lafayette College to PA, and, now on the OOS Snapshot menu page I have TWO PA sections AND when using the drop down of states in the Campus Search and I select Pennsylvania (PA)  I only have ONE campus when selecting Pennsylvania (PA) - and it is not Lafayette Please advise as I am tasked to enter new campuses today

**Comment by mlwoodward** [comment]
I talked to Thomas and he said that this should be resolved now.  Please confirm.  If resolved, I will close this issue.  If not, I will take a look.  Thanks.

**Comment by Ruth-DeTro** [comment]
Hi Michael,

Well, yes it is and no its not.  I am entering a test school now and will get back to you shortly with the results.  Thanks!  BTY:  Your voice mail in box is full or I would have left you a message.
Ruth D.

**Comment by mlwoodward** [comment]
I’m not sure I understand.  I look forward to your followup email.

**Comment by Ruth-DeTro** [comment]
I went in and tested with other campuses and it seems to be fine now.  I am assuming it was a cache issue with the server and that was why it did not automatically sort and merge the two PA campuses.

Gotta say – I thought it was really weird as I created the new campus page like I have always done and then kind of second-guessed myself so I watched your training video on adding, editing and removing campus pages.  I got more confident when I found I did it exactly as you did in the video, and then I panicked when I noticed I had two unduplicated PA sections (one as the first PA section showed on the OOS Campus Snapshots page with only Lafayette College (the new one I added) and the second (original) PA section in the proper alpha-order with Drexel University which already existed.  I am leaning towards the idea that the caches weren’t due to clear on the server when I entered it so a sort did not occur until later – when the cache was cleared. Make sense?

Because I have three new universities in three new states to add, I would greatly appreciate it if you would please let me know what you think the problem was that caused the duplication issue so I can notate a remedy should it happen again.  Maybe an “advanced” training video is in order?

Otherwise, I consider this issue done and you can close it in GitHub.

As for the other problem, I sure would like to know what caused the main menu to wig out and drop the OOS Links menu from the main menu.  Losing the OOS Links menu caused the three drop-down pages under it to show up on the main menu – which ended up looking horribly busy.  I could not find it anywhere on the main menu parent tree to fix myself but Thomas got it to reappear (I think he added it back to the menu) on the main menu and fixed that issue for me as well.

I sure would like to know how to fix this issue as well - should it happen again - causing one of the menus to completely disappear from the parent tree. Maybe an “advanced” video training?

Ruth D.

**Comment by Ruth-DeTro** [comment]
I tested it and yes – it seems to be resolved – but – I would appreciated an advanced video on how to fix should it happen again.

**Comment by mlwoodward** [comment]
We will create video and send it over.

**Comment by Ruth-DeTro** [comment]
Hi Michael,

Wow!   We are down to just 7 issues in GitHub!!

Just an FYI that I need a video showing how add new states to OOS page as well as to campus search and how to add campuses so I don’t run into that PA campus problem again.  I would appreciate it by Monday, if possible, as Ray is presenting on Wednesday and Thursday at Pasadena City College and Glendale College.

As for setting up a planning/meeting so you can sprint through the final issues, I will be available this coming Wednesday at any time.  Just let me know when you would like to set it – I assume we will be using Zoom?

Thanks!

Ruth D.

**Comment by mlwoodward** [comment]
Short video has been created.  If further questions, it would be good to either do a zoom meeting or in person meeting as I can specifically answer questions instead of broadly covering the topic.  Video link sent to Ruth.
