### ISSUE TITLE
Cannot get a CCC SSP page to link to in-page menu

### ISSUE THREAD

**Issue by Ruth-DeTro** [woodwarddesign/ccc-transfer#188]
I get how to make a new page (and watched video to make sure I wasn't missing anything) but the video only shows me how to link to website menu - not to in-page menu.  I want to link the Puente Program to the in-page menu just like your team did for me with the other CCC SSP programs at http://ccctransfer.org/student-service-prgm-links  (I.e., MESA, OPS, DSPS, etc.). I have unpublished the Puente page for now until I heard back from you - a video would be very nice for this special little trick.
Ruth D.

**Comment by mlwoodward** [comment]
This is fixed.
