### ISSUE TITLE
Deactivation of phone numbers on UC Campus pages

### ISSUE THREAD

**Issue by Ruth-DeTro** [woodwarddesign/ccc-transfer#190]
I have not been into the UC campuses section for some time.  This morning I had an email request from UC Merced to change some contact information.  When I made the change I noticed that on all UC campus sections the majority of the phone numbers have again become active – as they did in the past when I had Skype loaded (which is no longer on my hard drive). 
This issue does not show on the CSU Campus sections – only the UC campus sections.  It does not matter what browser I use (Chrome, Firefox, I.E., etc.) they all show the phone numbers as an active link. Please advise as to how I can deactivate the phone numbers. Thanks!

**Comment by Ruth-DeTro** [comment]
Noticed the phone numbers are now deactivated.  Thanks.  We can close this issue now?

**Comment by mlwoodward** [comment]
Correct.  This was updated on the day of the request.  I will close the issue.  Thanks!

**Comment by Ruth-DeTro** [comment]
Thank you!  Sorry for the late reply – busy with other issues/tasks.  But, wanted you to know I am not ignoring you. ☺
