### ISSUE TITLE
The scroll bar on the menu on the Campus Search page (where one can select a state or sytem type) still jumps from top to bottom rather than smoothly scrolling through the states on the scroll menu

### ISSUE THREAD

**Issue by Ruth-DeTro** [woodwarddesign/ccc-transfer#191]

**Comment by mlwoodward** [comment]
What browser is this happening on?  I can't replicate.  I can also make this box taller so that scrolling isn't as big as an issue.  Thoughts?

**Comment by Ruth-DeTro** [comment]
Hi Michael,

The problem with the college search scroll bar is the same in all Browsers that I try.

This is how it looks in Chrome – Version 42.0.2311.152 m: In Explorer – Version 11.0.9600.17207:
And FireFox - Version 37.0.2.
[See how funky the scroll bar looks][cid:image004.png@01D08E2E.E0AE6630][cid:image010.jpg@01D08E2E.E0AE6630]

Ruth D.

**Comment by mlwoodward** [comment]
@Ruth-DeTro Can you email me the images directly?  They did not come through on GitHub.

**Comment by Ruth-DeTro** [comment]
Odd… I emailed the images to you view email not GitHub.  Anyways, I attached that email to this one for you to view. Let me know if you got this one.
Ruth D.

**Comment by mlwoodward** [comment]
When you reply to these emails they go to Github.  As you can see from the actual emails attached above, they are Github emails not mike@woodwarddesigngroup.com mailto:mike@woodwarddesigngroup.com.  Please email to mike@woodwarddesigngroup.com mailto:mike@woodwarddesigngroup.com.  As the email that you replied to was a github email, I still have not received the screenshots.  Hope your Monday is off to a great start!

Thanks,

Michael Woodward
Owner | mike@woodwarddesigngroup.com mailto:mike@woodwarddesigngroup.com | 530-513-6663 tel:5305136663
Woodward Design Group http://www.woodwarddesigngroup.com/, 2500 England St., Chico, CA 95928

**Comment by mlwoodward** [comment]
We've done some additional work on this.  Please test on your end.  At this point it is scrolling smoothly on my PC on both IE (9,10,11) and Firefox version 38.  We can screen share so that you can show me any remaining issues with this.  If the issue remains, my only recommendation is to make the box taller.  Let me know your thoughts and results.

**Comment by mlwoodward** [comment]
The bar is now fixed for me, but the schools have disappeared.  Looking into the issue now.  Please confirm that scroll is now fixed on your device.

Thanks,

**Comment by mlwoodward** [comment]
Tracked down bug.  Conflicting error in the floating headers tools.  Working on patch.

**Comment by mlwoodward** [comment]
This is resolved.  Please review.  Have browser tested on several computers and devices.

**Comment by mlwoodward** [comment]
Have to fix javascript glitch on search page.

**Comment by mlwoodward** [comment]
Took 3 hours but was able to rewrite the two conflicting codes to make this work without affecting the search tool.  Please review and let me know thoughts.

**Comment by mlwoodward** [comment]
Approved by client.
