### ISSUE TITLE
This issue pertains to the AICCU Campus Snapshots page.  When one clicks on a campus name it should take the viewer directly to the campus snapshot rather than the intermediary page that is very sparse looking (also would eliminate an extra click for the viewer). 

### ISSUE THREAD

**Issue by Ruth-DeTro** [woodwarddesign/ccc-transfer#192]

**Comment by mlwoodward** [comment]
@Ruth-DeTro this is updated and I think it works really well.  Great idea!  Take a look and let me know what you think.  I will close this task for now.  We can reopen if any updates need to happen.

**Comment by Ruth-DeTro** [comment]
Perfect Michael!  Thanks. ☺
Ruth D.

**Comment by Ruth-DeTro** [comment]
Thanks and yes, I agree that it is much better and cleaner.
