### ISSUE TITLE
Floating Headers (Tables)

### ISSUE THREAD

**Issue by mlwoodward** [woodwarddesign/ccc-transfer#193]
Pages affective:

http://ccctransfer.org/ccc-transcript-legends-and-transcript-request-links
http://ccctransfer.org/ccc-transfer-center-websites-catalog-links

**Comment by Ruth-DeTro** [comment]
Yep, because the tables are so very long, these pages need floating table headers like we have on the assessment page.  Thanks!  Not sure why I could not get GitHub to hold this request.  Have a great holiday!
Enjoy your baby girl.  ☺
Ruth D.

**Comment by mlwoodward** [comment]
Writing custom script for this feature.  Will be wrapped up tomorrow afternoon.

**Comment by Ruth-DeTro** [comment]
Okay,

I will keep an eye out for it.

**Comment by mlwoodward** [comment]
Take a look at this page and let me know what you think.  If it looks good, I will add that into the other page too.  http://ccctransfer.org/ccc-transcript-legends-and-transcript-request-links

**Comment by mlwoodward** [comment]
Updated and completed!
