### ISSUE TITLE
More of a question right now than an issue:  Can we add a drop-down menu to the Campus Search menu on the horizontal menu bar?

### ISSUE THREAD

**Issue by Ruth-DeTro** [woodwarddesign/ccc-transfer#194]
I found another question while transcribing minutes - can a drop-down menu be added to the college search menu on the horizontal menu bar?

**Comment by mlwoodward** [comment]
It’s possible.  What are the perimeter’s for the dropdown?  What will it do?

Michael Woodward
Owner | mike@woodwarddesigngroup.com mailto:mike@woodwarddesigngroup.com | 530-513-6663 tel:5305136663
Woodward Design Group http://www.woodwarddesigngroup.com/, 142 W 2nd Street, Suite A, Chico, CA 95928

**Comment by Ruth-DeTro** [comment]
The drop down would act just like all other menu drop-downs that we have – they would take the user to a (new) page that will house historically black colleges & universities (HBCUs), tribal colleges, and Hispanics-friendly (HACU) colleges.  This page already exists on the OOS drop-down, however, HACUs are mostly in California – not out-of-state, so a counselor would not necessarily go to the OOS menu to look for a HACU or HBCU campus, but they would be more apt to look under the college search menu.  Make sense?

Make sense?

**Comment by mlwoodward** [comment]
So this isn’t the filter on the search page, but an actual dropdown on the navigation on the top similar to the Resources, CCC Links …. tabs?  And all the pages already exist?

Thanks,

Michael Woodward
Owner | mike@woodwarddesigngroup.com mailto:mike@woodwarddesigngroup.com | 530-513-6663 tel:5305136663
Woodward Design Group http://www.woodwarddesigngroup.com/, 142 W 2nd Street, Suite A, Chico, CA 95928

**Comment by Ruth-DeTro** [comment]
Not – they would not need to be added to the filter on the search page. Yes, I would rather keep each type of system separate – on their own pages.  No, not all these pages exist yet – the one that does is on the OOS drop-down menu and may get renamed.

This is NOT something I have high on my priority list – but just a question to you to see if it is possible in the future so I can take an answer back to the advisory in April.  Thanks for your quick response – but the other issues are more important and urgent to complete than this is.  I sent it now so I would not forget to ask. ☺

**Comment by mlwoodward** [comment]
Yes, this is something that can be done.  Just trying to gauge the difficulty.  : )  Would you need us to create the pages too?  Adding the link itself only takes a minute or two.  I can show you how or do it for you.  Very easy.  Depending on the pages, they could be easy to create or a little time consuming.  Thoughts?

**Comment by Ruth-DeTro** [comment]
Not if it is the same process of adding a drop-down to any other main (parent) menu then I know how to do that.
But, yes, I would  like a video training from you on this process (maybe a bit more advanced than a basic training video?) that I can share with my future successor.

As for creating the pages, I can do that too. As mentioned above, yes, I would  like a video training from you on this process (maybe a bit more advanced than a basic training video?) that I can share with my future successor.

I just did not want to explore and possibly mess up the dbase structure of the college search.

This campus is a ghost town so we are all leaving here at 11 am.  I will periodically check my email for anything from you and try to respond as quickly as possible.  Otherwise, see you in January.

Ruth D.

**Comment by mlwoodward** [comment]
It is the same process as adding a drop-down to any other main / parent menu.  Did you still need a new video on that?  I think we had that covered.  I can create one if needed.  Maybe a Zoom training would work better than a training video in the case of pages.  That way I can answer specific questions instead of making assumptions on what is needed.  I can then create a follow up video covering the same items, if you would like.

If you want we can do the first drop-down together so that you can be at ease and not worry if everything is correct.  : )  Enjoy the rest of your day…and the weekend!  

Mike

**Comment by mlwoodward** [comment]
@Ruth-DeTro just wanted to check into this.  Is this something that we are going to do or just still in the research phase?

**Comment by Ruth-DeTro** [comment]
Nope – more of a question than a GitHub request. ☺  Still in research phase.
Ruth D.

**Comment by mlwoodward** [comment]
Should we close this one?

Michael Woodward
Owner | mike@woodwarddesigngroup.com mailto:mike@woodwarddesigngroup.com | 530-513-6663 tel:5305136663
Woodward Design Group http://www.woodwarddesigngroup.com/, 2500 England St., Chico, CA 95928

**Comment by Ruth-DeTro** [comment]
Good morning Michael,

Sure.   Let’s close this one.
Ruth D.

**Comment by mlwoodward** [comment]
Sounds great.
