### ISSUE TITLE
Add back in the auto update for all pages.

### ISSUE THREAD

**Issue by Ruth-DeTro** [woodwarddesign/ccc-transfer#197]
This was done prior to server failure and needs to be added back to all pages (note: already on campus ages but not re-added to all other pages.  Prior to failure you had a cell that added: "Updated by TCW" and then a calendar auto-insert.

**Comment by mlwoodward** [comment]
@Ruth-DeTro do you want this added to the University Announcements?  It has been updated everywhere else that it's appropriate.  Please note that manually entered date in the body will need to be removed as you update this.  You will also need to select a date in the field when saving the existing pages.  That will add in the new date on pages as you edit.  I didn't want to override your work.  : )  See the example on the front page.

**Comment by Ruth-DeTro** [comment]
HI Michael,

Yes, I noticed it is back… thanks!  No, not needed for announcements. ☺

**Comment by mlwoodward** [comment]
Issue with space below date.

**Comment by mlwoodward** [comment]
Updated.  Sent email to Ruth for review.

**Comment by mlwoodward** [comment]
Heard back from Ruth.  Looks good.
