### ISSUE TITLE
Add video button to TCW homepage and produce video tutorial on how to link, etc.

### ISSUE THREAD

**Issue by Ruth-DeTro** [woodwarddesign/ccc-transfer#198]
As per our phone conversation, please add back the spacing between top of the list serve signup box and bottom of the news feed column and place a video button there.  Then, please create and send to me a video tutorial on how to link a video, webinar, etc., to the button.

**Comment by mlwoodward** [comment]
@Ruth-DeTro I'm working on wrapping up items this week.  I wanted to get more feedback on this.  Do you want a graphic based button or just a text based button?  You mentioned wanting to know how to link to various items from this button.  Do you want other buttons built (and hidden) too so that they are ready to go.  Buttons for webinar and others?

**Comment by Ruth-DeTro** [comment]
Hi Michael,

I sent your question to Ray so the answer will cover what he has in mind as well.  Hopefully he will get back to me today.

Ruth D.

**Comment by mlwoodward** [comment]
@Ruth-DeTro just checking in on feedback on this one.  : )

**Comment by mlwoodward** [comment]
Notes from Ruth in regards to Ray's goals...

Here are his requests:
1.   He would like the button placed on the homepage just above the TECH SUPPORT button (where it will be most visible).
2.   He would like the video button to be labeled “VIDEOs”
3.   He would like the button to be attached to a basic TCW page template that will allow me to add an introduction and various links to it.

**Comment by mlwoodward** [comment]
Has been created.  Video can be found here: https://vimeo.com/129161650
Password: ccc2015

Let me know your thoughts.  I also adjusted the spacing slightly from the version in the video.

**Comment by mlwoodward** [comment]
Approved by client.  H3 class note: tech-support-button video-button
