### ISSUE TITLE
Design revisions - Panels, markup specific changes

### ISSUE THREAD

**Issue by bodhiprice** [woodwarddesign/ccc-transfer#22]
This issue is needed because the prototype and Drupal site have markup that is not in sync. Rather than copying work from prototype, it has to be done manually.

**Comment by DirectorWho** [comment]
I do realize this issue is 2 weeks old. All current design revisions are taking place in a separate branch. I do agree though this is an issue that needs to be addressed on future projects.

**Comment by bodhiprice** [comment]
This is actually not complete.

**Comment by bodhiprice** [comment]
It's on my end though - I need to make a couple custom Panels layouts.

**Comment by bodhiprice** [comment]
This is done.
