### ISSUE TITLE
Add "search TCW" to search bar

### ISSUE THREAD

**Issue by AMagnifico** [woodwarddesign/ccc-transfer#28]
The search bar does not say “Search TCW” like it does on homepage.

**Comment by DirectorWho** [comment]
I've looked at both branches, the one we develop on as well as the one they review, and they all have "Search TCW..." in the search box, like the homepage.

**Comment by mlwoodward** [comment]
I think that this is on the Pantheon version of the site.

Thanks,

Michael Woodward
Owner | mike@woodwarddesigngroup.com | 530-513-6663
Woodward Design Group, 142 W 2nd Street, Suite A, Chico, CA 95928

**Comment by DirectorWho** [comment]
I believe this is an update that should be made from within the database & not a design update.

**Comment by bodhiprice** [comment]
OK, this is done.
