### ISSUE TITLE
Design menu's to look the same on all pages

### ISSUE THREAD

**Issue by AMagnifico** [woodwarddesign/ccc-transfer#29]
We would like the main horizontal menu (as well as the footer menu) to look the same on all pages - with the text bolded.

**Comment by DirectorWho** [comment]
This needs clarification. I'm not patient enough to guess what exactly they're wanting changed. Specifically what needs changed. Do they want to add a border at the top of the bottom? Is the space above and below the menu links giving the client the illusion that the fonts are a different size? (They are the same size)

They've asked for numerous minute changes and some of these "issues" being placed here come of like they're seeing cached versions of the templates.

**Comment by DirectorWho** [comment]
This has been corrected in the design branch
