### ISSUE TITLE
Bold text on Tech Support Button 

### ISSUE THREAD

**Issue by AMagnifico** [woodwarddesign/ccc-transfer#30]
The Tech Support button – can you bold the text?

**Comment by bodhiprice** [comment]
@DirectorWho How would you like to handle this? Would you prefer to add Roboto Slab bold to the mix? Google web fonts has it right at the edge of being too heavy a font stack with the total number of font faces/weights at 5.

**Comment by DirectorWho** [comment]
@friendlymachine It's already rather prominent. Unless I'm seeing something different than others, i think we should leave it alone for now.

**Comment by bodhiprice** [comment]
OK, let's close this one then.
