### ISSUE TITLE
Change News to Newsfeeds on the Neewsfeed header 

### ISSUE THREAD

**Issue by AMagnifico** [woodwarddesign/ccc-transfer#31]
The Newsfeeds header on the standard page template only states “News” – not “Newsfeeds”.
a.       BTW:  I like the location of the More News on the standard page template than I do the on the TCW homepage mockup/template.

**Comment by DirectorWho** [comment]
There are only 3 pages in the template. None of them have these issues that are being placed here. Please Clarify.  --- I've now been informed that these series of edit is for the pantheon site. That clears things up.

**Comment by DirectorWho** [comment]
This appears to be corrected on the drupal site.
