### ISSUE TITLE
Change "us know" to "Let us know" on the contact us link 

### ISSUE THREAD

**Issue by AMagnifico** [woodwarddesign/ccc-transfer#32]
The contact us link in the disclaimer on the standard page template is linked to “us know” – can you link it to “Let us know” like you did on the homepage template.

**Comment by DirectorWho** [comment]
This is something that still needs corrected on the drupal website.

**Comment by hmickelson** [comment]
I can't edit this because I don't have proper permissions using the "Editor" user. Let me know course of action from here.

**Comment by DirectorWho** [comment]
@hmickelson I'll take care of this once i get an account for the site.
