### ISSUE TITLE
Fix migrated content paths, add to menu and change content type from article

### ISSUE THREAD

**Issue by bodhiprice** [woodwarddesign/ccc-transfer#37]
The content would only migrate into the site as article content type. Also, no paths came over from the Joomla site and no content has been added to menu. Please find the content listed in the menu of the current site:

http://ccctransfer.org/

Find it's match among the content that was imported into Drupal using the content search tool, fix the path and add to menu and finally convert to either Basic page or University announcement content type as appropriate.

Let me know if you have questions.

**Comment by hmickelson** [comment]
This is done.
