### ISSUE TITLE
Footer: Font on dev site is different than on the prototype

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#55]
Here's the issue Mike mentioned
![footer-font-weight](https://cloud.githubusercontent.com/assets/7529130/3273689/efc36222-f326-11e3-90d8-a686b43a7725.jpg)

**Comment by bodhiprice** [comment]
@DirectorWho  @wdg-thomas  I just adjusted the font weight. If it looks OK, this can be closed.

**Comment by DirectorWho** [comment]
@friendlymachine @wdg-thomas Looks good. The client had mentioned in a revision of the html template that they wanted the fonts in the footer to be heavier. This appears to do the job. I'll go in during the revisions i'm making of for the css and adjust the font-size of the copyright to be the same size. This will go along with a number of other adjustments i'll make there.
