### ISSUE TITLE
Header: Under left logo:  Add "Built for CCC Counselors…" blurb

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#57]

**Comment by DirectorWho** [comment]
For reference, the full site slogan is "Built for CCC Counselors by CCC Counselors".

**Comment by DirectorWho** [comment]
@friendlymachine @wdg-thomas I need an admin account to take care of this the correct way. I currently have no account setup under my email address ("access denied"). Can we please correct this?

**Comment by bodhiprice** [comment]
I'll add the login to the wiki.

**Comment by DirectorWho** [comment]
The CSS for this was already in place (thanks john) & the slogan has been added in the appropriate field within admin/config/system/site-information. It should be noted since the account was created under my email i already changed the name & password. If this is an issue for anyone i apologize.
