### ISSUE TITLE
Remove cellpadding, cellspacing, border & inline styles from tables. 

### ISSUE THREAD

**Issue by DirectorWho** [woodwarddesign/ccc-transfer#58]
A specific example of this is located [Here](http://dev-ccc-transfer.gotpantheon.com/ccc-student-service-program-links)

**Comment by DirectorWho** [comment]
@wdg-thomas If this is an example of something that is out of scope of the contract then it should at least be brought to the attention of Ruth.

**Comment by bodhiprice** [comment]
I think we should add some basic table styling. It costs so little and will make a big difference. They look  rough right now.

**Comment by DirectorWho** [comment]
I agree, but the tables are still overriding the stylesheet.
