### ISSUE TITLE
Clarify Drop down menus on desktop

### ISSUE THREAD

**Issue by DirectorWho** [woodwarddesign/ccc-transfer#59]
@wdg-thomas @friendlymachine I think this may be a quick task to take care of to help communicate the additional menu options. Think i will add a simple icon to the right of menu parents.  Thoughts?

**Comment by DirectorWho** [comment]
These changes have are only targeted at the $desk breakpoint

**Comment by bodhiprice** [comment]
@DirectorWho Are you talking about a little arrow? If so, I would put it on right.
