### ISSUE TITLE
Banner Images

### ISSUE THREAD

**Issue by mlwoodward** [woodwarddesign/ccc-transfer#64]
We received permission from the client to use the current banner.  They also provided a few additional photos for when they switch out on load. 

[Athletics Crew_UCSB.JPG | uploaded via ZenHub](https://www.zenhub.io/files/539f2c33470ee2cd19001358)

[Campus with Storke Tower_UCSB.jpg | uploaded via ZenHub](https://www.zenhub.io/files/539f2c3d470ee2cd19001359)

[Pep Band_UCSB.JPG | uploaded via ZenHub](https://www.zenhub.io/files/539f2c45470ee2cd1900135a)

[UCSB-Judicial-Affairs-Office.jpg | uploaded via ZenHub](https://www.zenhub.io/files/539f2c4a470ee2cd1900135b)

**Comment by bodhiprice** [comment]
This is done, but one of the images provided was too small and two of the others have aspect ratios that don't work well in the space provided. Two images are in rotation now, the others are unpublished pending review/edit.

**Comment by mlwoodward** [comment]
I will review with the client at our weekly meeting.  I will keep you posted.
