### ISSUE TITLE
Design: Navigation ambiguity on Best Practices page

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#66]
Location: Resources > [Best Practices](http://dev-ccc-transfer.gotpantheon.com/best-practices)

On the current Best Practice page I have an in-page menu that is split into 6 different sections but is not on the test site is all runs together without indication of each section. 

![best-practices-table-nav](https://cloud.githubusercontent.com/assets/7529130/3304677/bf11b0be-f64d-11e3-818c-9f5011014d49.png)

**Comment by DirectorWho** [comment]
The menu items now link to items on the page. I'm looking into the content issue.

**Comment by ghost** [comment]
The issue she has is that the inside table borders are not defined  |  

| Best Practices | Guidelines |
| --- | --- |
| Charts …  | Scholarship …  |

**Comment by DirectorWho** [comment]
@wdg-thomas Alright, I'll add that to my list
