### ISSUE TITLE
Content: Missing Page: Conference & Materials under Resources

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#67]
For ref. http://ccctransfer.org/conferences-and-materials

Conference & Materials is not showing under Resources like on the orig.

**Comment by bodhiprice** [comment]
This isn't missing. They had a duplicate link. The 'Resources' link and 'Conferences and Materials' pointed to the same page, so I removed one.

**Comment by DirectorWho** [comment]
This issue appears to be resolved.
