### ISSUE TITLE
Content: Missing content: Directories

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#68]
Joomla/source: http://ccctransfer.org/directories

Dev: http://dev-ccc-transfer.gotpantheon.com/directories

On the Joomla site, the Directories page has an in-page menu that split out into 7 sections

Note: Content appears to be outdated?

**Comment by DirectorWho** [comment]
Looking into this.

**Comment by ghost** [comment]
Confirmed. Closing issue.
