### ISSUE TITLE
Design: Legislation, Reports & Research in-page menu issue

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#69]
Joomla/source: http://ccctransfer.org/research

dev: http://dev-ccc-transfer.gotpantheon.com/legislation-reports-research

The Legislation, Reports & Research by System page also has an in-page menu that is split out by system/by type of content – it is included in the migration but is scattered all over the page.

**Comment by DirectorWho** [comment]
This has been fixed.
