### ISSUE TITLE
Design: Scholarships: in-page menu issue

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#70]
joomla/source: http://ccctransfer.org/resources/scholarship-links

dev: http://dev-ccc-transfer.gotpantheon.com/scholarship-links

The Scholarship page’s in-page menu was migrated over (it has six sections) but is scattered all over the page and not linked to anything.

**Comment by DirectorWho** [comment]
John is working on the ckeditor config to have it solve the linking issue. Unfortunately it is likely that the name attributes will need to be added back into the content. this will affect any page with one of her custom table menus.

**Comment by DirectorWho** [comment]
This has been corrected.
