### ISSUE TITLE
Make tables responsive

### ISSUE THREAD

**Issue by bodhiprice** [woodwarddesign/ccc-transfer#74]

**Comment by ghost** [comment]
Which tables specifically? I'll need to make issues for these to make sure none get missed

**Comment by bodhiprice** [comment]
It will be hard to quantify - all of them, of which there are dozens. What I do should cover them al.

**Comment by bodhiprice** [comment]
After group discussion on the improper use of tables in content on existing site, decision is to forego responsive tables on this site.
