### ISSUE TITLE
Design: Style CCC Equivalencies sort table

### ISSUE THREAD

**Issue by bodhiprice** [woodwarddesign/ccc-transfer#78]
This is currently located here:
http://dev-ccc-transfer.gotpantheon.com/ccc-english-and-math-assessment-course-equivalency-table

**Comment by bodhiprice** [comment]
Reassigned this to Scott as he is actually doing the work.

**Comment by DirectorWho** [comment]
Yep, tackling this while i work with the other tables.

**Comment by ghost** [comment]
If we had more budget I'd say tease out the Compare Selections from Reset a bit, but I'm guessing this is as good as we need unless we get strong feedback otherwise
