### ISSUE TITLE
Fix main menu overlap upon screen size reduction

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#88]
Client says 

> when I decreased page width the menus overlap – this won’t happen when viewed on a phone or tablet, right?
> ![menu-break](https://cloud.githubusercontent.com/assets/7529130/3333347/2f7185a0-f7f2-11e3-98e7-48d953f3a46b.png)

**Comment by DirectorWho** [comment]
@wdg-thomas This is a duplicate. This task has already been completed. See https://github.com/woodwarddesign/ccc-transfer/issues/84

**Comment by ghost** [comment]
Ok. On stuff like this, go ahead and tag with a  **duplicate** label. I'll close this one then.
