### ISSUE TITLE
School Search page: Blocks running together

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#90]
![blocks running together](https://cloud.githubusercontent.com/assets/7529130/3333632/b793f1cc-f7f5-11e3-9c3f-80a9ded4b2d8.png)

**Comment by DirectorWho** [comment]
That is an issue that happens on resize. There does seem to be an issue with those blocks when you filter certain results. Examples, CSU, AICCU, & Hawaii. The others format normally. I can certainly make this a seperate issue, but thought for now i'd place this here to avoid spam. 
[school-finder.jpg | uploaded via ZenHub](https://www.zenhub.io/files/53a359c7338cd6d26e000dcb)

**Comment by bodhiprice** [comment]
I think this is fixed. There is a delay on the jQuery plugin that loads the schools. If the page loads slowly, it was causing this issue. I made some edits and can no longer replicate. Needs to be verified.

**Comment by ghost** [comment]
http://dev-ccc-transfer.gotpantheon.com/school-search
appears to be working. closing
