### ISSUE TITLE
Menu: CSU Links: Missing "CSU Campuses"

### ISSUE THREAD

**Issue by ghost** [woodwarddesign/ccc-transfer#94]
![csu campuses on old site](https://cloud.githubusercontent.com/assets/7529130/3333913/b977f3c8-f7f8-11e3-9187-acf1b54b4144.png)

![csu campuses missing](https://cloud.githubusercontent.com/assets/7529130/3333914/b978e42c-f7f8-11e3-8fda-164a77908e91.png)

**Comment by DirectorWho** [comment]
CSU Links & CSU Campuses were linking to the same page on their original site. This is also the case for UC.

**Comment by ghost** [comment]
The client is used to seeing the _primary navigation_ with links to subsections below. We need to match the existing behavior on this one (and other like it). Mike says the  [Special Menu Items](https://www.drupal.org/project/special_menu_items) module should work for this.

**Comment by bodhiprice** [comment]
This will create a dead link in the primary nav if I'm not mistaken. This would be fine if all of them are 'dead', but when they click on the 'link' nothing will happen. Duplicating links is is preferable in my view. Plus, this will probably jack up the mobile version of the menu which reads links from the first level items. 

The preferred solution is for her to make a page like she did for Resources. She told  me the old developer had set it up that way (double links) and that what we were suggesting made more sense to her.

**Comment by DirectorWho** [comment]
I agree with John.

**Comment by ghost** [comment]
Awesome: duplicate at will. This applies to the others. I can make separate tasks though

**Comment by bodhiprice** [comment]
The preferred solution is for her to make a page like she did for Resources, not duplicate. I can make the pages.

**Comment by ghost** [comment]
good deal. same with the other pages

**Comment by bodhiprice** [comment]
Done.
