### ISSUE TITLE
Correct formatting on AICCU schools pages

### ISSUE THREAD

**Issue by DirectorWho** [woodwarddesign/ccc-transfer#98]

**Comment by bodhiprice** [comment]
@DirectorWho Can you provide more info? Is there a link? Those schools show up in multiple places.

**Comment by bodhiprice** [comment]
Was this supposed to be assigned to me? Sorry if I'm hijacking your issue!

**Comment by DirectorWho** [comment]
@friendlymachine I thought i left it unassigned. I'll take care of it. Wasn't trying to add to your work load.

**Comment by DirectorWho** [comment]
Adjusted header margin values on AICCU nodes, design branch.

**Comment by ghost** [comment]
ok.
